### ISSUE TITLE
generate analysis for JavaScript project?

### ISSUE THREAD

**Issue by micahstubbs** [PRIMITIVE-IO/primitive#22]
greetings, thanks for making & publishing this impressive tool. What's the best way to generate an analysis for a JS project?

being a curious person, I thought I'd try to create an analysis for an open source JavaScript project and view the analysis in PrimitiveVR.  I've been working with this [material-ui](https://github.com/mui-org/material-ui) library recently, so thought I've have a go at visualizing it.

https://github.com/PRIMITIVE-IO/primitive#running-your-own-analysis-free-for-non-commercial-use

I followed the guide here, but saw an error from the IntelliJ Idea plugin that sounds it like was expecting a Java project.

![screenshot 1548576757](https://user-images.githubusercontent.com/2119400/51798506-4f5a3b00-21c8-11e9-85a0-7c4f5a8d2c53.png)

What's the best way to generate an analysis for a JS project?

<details><summary>error text</summary>
java.lang.NoClassDefFoundError: io/primitive/codebaseunity/exception/CouldNotCreateOutputDirectoryException
	at io.primitive.intellij.StaticAnalyzeAction.actionPerformed(StaticAnalyzeAction.kt:34)
	at com.intellij.openapi.actionSystem.ex.ActionUtil$1.run(ActionUtil.java:258)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:275)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem$ActionTransmitter.lambda$actionPerformed$0(ActionMenuItem.java:287)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.runOnOwnContext(FocusManagerImpl.java:283)
	at com.intellij.openapi.wm.impl.IdeFocusManagerImpl.runOnOwnContext(IdeFocusManagerImpl.java:106)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem$ActionTransmitter.actionPerformed(ActionMenuItem.java:277)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem.lambda$fireActionPerformed$0(ActionMenuItem.java:111)
	at com.intellij.openapi.application.TransactionGuardImpl.runSyncTransaction(TransactionGuardImpl.java:88)
	at com.intellij.openapi.application.TransactionGuardImpl.lambda$submitTransaction$1(TransactionGuardImpl.java:111)
	at com.intellij.openapi.application.TransactionGuardImpl.submitTransaction(TransactionGuardImpl.java:120)
	at com.intellij.openapi.application.TransactionGuard.submitTransaction(TransactionGuard.java:122)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem.fireActionPerformed(ActionMenuItem.java:111)
	at com.intellij.ui.plaf.beg.BegMenuItemUI.doClick(BegMenuItemUI.java:522)
	at com.intellij.ui.plaf.beg.BegMenuItemUI.access$300(BegMenuItemUI.java:35)
	at com.intellij.ui.plaf.beg.BegMenuItemUI$MyMouseInputHandler.mouseReleased(BegMenuItemUI.java:544)
	at java.awt.Component.processMouseEvent(Component.java:6548)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3325)
	at java.awt.Component.processEvent(Component.java:6313)
	at java.awt.Container.processEvent(Container.java:2237)
	at java.awt.Component.dispatchEventImpl(Component.java:4903)
	at java.awt.Container.dispatchEventImpl(Container.java:2295)
	at java.awt.Component.dispatchEvent(Component.java:4725)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4889)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4526)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4467)
	at java.awt.Container.dispatchEventImpl(Container.java:2281)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4725)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:764)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
	at java.awt.EventQueue$4.run(EventQueue.java:737)
	at java.awt.EventQueue$4.run(EventQueue.java:735)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:734)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:719)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:664)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:363)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.lang.ClassNotFoundException: io.primitive.codebaseunity.exception.CouldNotCreateOutputDirectoryException PluginClassLoader[io.primitive.primitive-intellij-plugin, 1.0] com.intellij.ide.plugins.cl.PluginClassLoader@5c65b644
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:49)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 51 more
</details>

**Comment by micahstubbs** [comment]
ah, I see now that the IDEA plugin only supports Java and Kotlin for now. 👌 

> Initial release including support for Java and Kotlin visualization.

 https://plugins.jetbrains.com/plugin/11587-primitive-vr-java-analyzer

maybe there's another way to analyze JS?  maybe some clever hack where I wrap my JS inside of a Java project? 🤔

**Comment by micahstubbs** [comment]
```java
java.lang.ClassNotFoundException: io.primitive.codebaseunity.exception.CouldNotCreateOutputDirectoryException 
```
or maybe is this a permissions problem? looking closer, it looks like IDEA or the Primitive plugin may not have permission to write to my local disk to create a folder to put the analysis in 🤔

**Comment by atonalfreerider** [comment]
@micahstubbs here is the result of the JS analyzer for material-ui:
https://drive.google.com/drive/folders/1LQhTDqtfA3NkOEO1CTDBIks1o3nyvYFD

Put the material-ui folder with the containing analysis in the analyzed-programs folder.

Also - please make sure to update Primitive to the latest build on Steam - otherwise the analysis won't load (Primitive will auto-update if you restart Steam)

Thanks!

**Comment by jayb967** [comment]
Is javascript available for the Visual Studio IDE? I only saw the C# plugin.

**Comment by atonalfreerider** [comment]
@jayb967 the JS analyzer is still unreleased. However you can still see the syntax highlighted text and structure of your project by using the intellij plugin

**Comment by TheMightyPilot** [comment]
Is there any estimated time when this JS analyser will be released?
